export const LOGIN_URL = "http://localhost:5000/login"
export const SIGNUP_URL = "http://localhost:5000/signup"
export const STOCKS_SHOWALL_URL = "http://localhost:5000/stocks/showall"
export const NEWS_URL = "http://localhost:5000/topnews"
export const SEARCH_URL = "http://localhost:5000/stocks/search?q="
export const BASE_STOCK_URL = "http://localhost:5000/stocks/"
export const BULK_STOCK = "http://localhost:5000/stocks/bulk"
export const BULK_DELETE = "http://localhost:5000/mystocks/bulk"
